version: "3"
services: 
    db:
        image: postgres
        restart: always
        environment:
          POSTGRES_PASSWORD: postgres    
          POSTGRES_USER: postgres    
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    service-a:
        image: service-a
        container_name: service-a
        ports: 
            - 9080:9080
            - 9443:9443
    service-b:
        image: service-b
        container_name: service-b
        ports: 
            - 9081:9081
            - 9444:9444
        depends_on: 
            - service-a
